export const itemData = [
  {
    lectureId: 1,
    className: "lecture",
    objectIndex: 1,
    lectureTitle: "lecture 1",
    lectureDescription: "D1",
  },
  {
    sectionId: 1,
    className: "section",
    sectionTitle: "Section 1",
    sectionDescription: "d1",
    objectIndex: 1,
  },
  {
    lectureId: 2,
    className: "lecture",
    objectIndex: 2,
    lectureTitle: "lecture 2",
    lectureDescription: "D2",
  },
  {
    lectureId: 3,
    className: "lecture",
    objectIndex: 3,
    lectureTitle: "lecture 3",
    lectureDescription: "D3",
  },
  {
    sectionId: 2,
    className: "section",
    sectionTitle: "Section 2",
    sectionDescription: "d2",
    objectIndex: 2,
  },
  {
    lectureId: 4,
    className: "lecture",
    objectIndex: 4,
    lectureTitle: "lecture 4",
    lectureDescription: "D4",
  },
  {
    lectureId: 5,
    className: "lecture",
    objectIndex: 5,
    lectureTitle: "lecture 5",
    lectureDescription: "D5",
  },
  {
    lectureId: 6,
    className: "lecture",
    objectIndex: 6,
    lectureTitle: "lecture 6",
    lectureDescription: "D6",
  },
  {
    sectionId: 3,
    className: "section",
    sectionTitle: "Section 3",
    sectionDescription: "d3",
    objectIndex: 3,
  },
  {
    lectureId: 7,
    className: "lecture",
    objectIndex: 7,
    lectureTitle: "lecture 7",
    lectureDescription: "D7",
  },
  {
    lectureId: 8,
    className: "lecture",
    objectIndex: 8,
    lectureTitle: "lecture 8",
    lectureDescription: "D8",
  },
];
